[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENV = "make netlify"

[context.deploy-preview]
  command = "make netlify"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.55.6"
